#!/bin/sh

# Quick Guide - Grid Merge Workflow

echo "════════════════════════════════════════════════════════"
echo "  GRID MERGE - Quick Reference Guide"
echo "════════════════════════════════════════════════════════"
echo ""

echo "📋 CONCEPT:"
echo "  Grid layer (dari QGIS) dimerge ke glmap.mbtiles SEKALI SAJA"
echo "  Next run hanya merge drone imagery baru"
echo ""

echo "🎯 FIRST TIME SETUP:"
echo "════════════════════════════════════════════════════════"
echo "1. Convert grid di QGIS → grid_layer.mbtiles"
echo "2. Upload ke server: /app/data/grid_layer.mbtiles"
echo "3. Run: ./generate-config-incremental.sh"
echo ""
echo "   Result:"
echo "   ✓ Grid merged to glmap.mbtiles (one-time)"
echo "   ✓ All drone files merged to glmap.mbtiles"
echo "   ✓ Flag created: .grid_merged"
echo ""

echo "⚡ UPLOAD FILE BARU (Fast Mode):"
echo "════════════════════════════════════════════════════════"
echo "1. Upload: new_drone_123.mbtiles to /app/data/"
echo "2. Run: ./generate-config-incremental.sh"
echo ""
echo "   Result:"
echo "   ✓ Grid merge SKIPPED (flag exists)"
echo "   ✓ Only new file merged (~2-5 seconds!)"
echo ""

echo "🔧 MAINTENANCE COMMANDS:"
echo "════════════════════════════════════════════════════════"
echo ""
echo "# Check grid status:"
echo "  [ -f /app/data/.grid_merged ] && echo 'Grid already merged' || echo 'Not merged'"
echo ""
echo "# Check merged drone files:"
echo "  wc -l /app/data/.merged_files.log"
echo ""
echo "# Check glmap tiles count:"
echo "  sqlite3 /app/data/glmap.mbtiles 'SELECT COUNT(*) FROM tiles;'"
echo ""
echo "# View merged files list:"
echo "  cat /app/data/.merged_files.log"
echo ""

echo "🔄 RESET OPTIONS:"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Option 1: Reset grid merge only"
echo "  rm /app/data/.grid_merged"
echo "  rm /app/data/glmap.mbtiles"
echo "  ./generate-config-incremental.sh"
echo ""
echo "Option 2: Reset drone merge (keep grid)"
echo "  rm /app/data/.merged_files.log"
echo "  rm /app/data/glmap.mbtiles"
echo "  ./generate-config-incremental.sh"
echo ""
echo "Option 3: Nuclear reset (everything from scratch)"
echo "  rm /app/data/.grid_merged"
echo "  rm /app/data/.merged_files.log"
echo "  rm /app/data/glmap.mbtiles"
echo "  ./generate-config-incremental.sh"
echo ""

echo "📊 FILE STRUCTURE:"
echo "════════════════════════════════════════════════════════"
echo "/app/data/"
echo "  ├── grid_layer.mbtiles       # Grid original (from QGIS)"
echo "  ├── glmap.mbtiles             # Merged: grid + drones"
echo "  ├── .grid_merged              # Flag: grid already merged"
echo "  ├── .merged_files.log         # Log: drone files merged"
echo "  └── *.mbtiles                 # Individual drone files"
echo ""

echo "✅ VALIDATION:"
echo "════════════════════════════════════════════════════════"
echo ""
echo "# Check grid tiles in glmap:"
echo "  sqlite3 /app/data/glmap.mbtiles \\"
echo "    'SELECT COUNT(*) FROM tiles WHERE zoom_level < 10;'"
echo ""
echo "# Check drone tiles in glmap:"
echo "  sqlite3 /app/data/glmap.mbtiles \\"
echo "    'SELECT COUNT(*) FROM tiles WHERE zoom_level >= 15;'"
echo ""
echo "# List all tables:"
echo "  sqlite3 /app/data/glmap.mbtiles '.tables'"
echo ""
echo "# View metadata:"
echo "  sqlite3 /app/data/glmap.mbtiles 'SELECT * FROM metadata;'"
echo ""

echo "⚠️  IMPORTANT:"
echo "════════════════════════════════════════════════════════"
echo "• Grid layer merge hanya 1x (efisien!)"
echo "• Jangan hapus grid_layer.mbtiles (untuk reset)"
echo "• Flag .grid_merged control grid merge behavior"
echo "• Backup .merged_files.log untuk track history"
echo ""

echo "🚀 TYPICAL WORKFLOW:"
echo "════════════════════════════════════════════════════════"
echo ""
echo "Day 1: First setup"
echo "  ./generate-config-incremental.sh  → 3-5 minutes"
echo ""
echo "Day 2: Upload 1 new file"
echo "  ./generate-config-incremental.sh  → 2-5 seconds ⚡"
echo ""
echo "Day 3: Upload 5 new files"
echo "  ./generate-config-incremental.sh  → 10-25 seconds ⚡"
echo ""
echo "Week 2: Total 100 files"
echo "  ./generate-config-incremental.sh  → Still 2-5 sec per new file!"
echo ""

echo "════════════════════════════════════════════════════════"
echo "  Ready to use! Run: ./generate-config-incremental.sh"
echo "════════════════════════════════════════════════════════"
