#!/bin/bash

# README: Enhanced Generate Config dengan Incremental Merge & Grid Layer

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   Enhanced Tileserver Config Generator dengan Grid Layer      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 NEW FEATURES:"
echo "════════════════"
echo "1. ✨ INCREMENTAL MERGE - Hanya merge file baru (tidak dari awal)"
echo "2. 🗺️  GRID LAYER - Tambah layer SHP sebagai base layer"
echo "3. 📊 MERGE TRACKING - Log file yang sudah dimerge"
echo "4. ⚡ FAST UPDATES - Upload file baru jadi cepat!"
echo ""

echo "🎯 LAYER STACK (dari bawah ke atas):"
echo "═══════════════════════════════════════"
echo "  Layer 1 (Bottom): Grid 36 HA (pink grid - dari SHP)"
echo "  Layer 2 (Top):    GLMap (drone imagery - dari mbtiles)"
echo ""

echo "📂 FILE STRUCTURE:"
echo "═══════════════════"
echo "/app/data/"
echo "├── GRID_DRONE_36_HA_EKSISTING_POTENSI 3/"
echo "│   └── GRID_36_HA_EKSISTING_POTENSI.shp  (Grid shapefile)"
echo "├── grid_layer.mbtiles                     (Converted grid - created once)"
echo "├── glmap.mbtiles                          (Merged drone tiles)"
echo "├── .merged_files.log                      (Tracking merged files)"
echo "└── *.mbtiles                              (Individual drone imagery)"
echo ""

echo "🚀 INSTALLATION & SETUP:"
echo "═════════════════════════"
echo "Step 1: Install Tippecanoe (untuk vector tiles)"
echo "  ./install-tippecanoe.sh"
echo ""
echo "Step 2 (Alternative): Jika tippecanoe gagal, gunakan GDAL"
echo "  ./convert-grid-raster.sh"
echo ""
echo "Step 3: Run generate config pertama kali"
echo "  ./generate-config-incremental.sh"
echo ""

echo "💡 WORKFLOW - FIRST TIME:"
echo "══════════════════════════"
echo "1. Upload semua file .mbtiles ke /app/data/"
echo "2. Pastikan folder GRID_DRONE_36_HA_EKSISTING_POTENSI 3/ ada"
echo "3. Run: ./generate-config-incremental.sh"
echo "4. Wait... (pertama kali akan merge semua file)"
echo "5. Done! Container restart otomatis"
echo ""

echo "⚡ WORKFLOW - UPLOAD FILE BARU:"
echo "════════════════════════════════"
echo "1. Upload file baru .mbtiles ke /app/data/"
echo "2. Run: ./generate-config-incremental.sh"
echo "3. Done! (hanya merge file baru - SUPER CEPAT!)"
echo ""

echo "📊 HOW IT WORKS:"
echo "═════════════════"
echo "Incremental Merge Logic:"
echo "  • Script check file .merged_files.log"
echo "  • Cari file yang belum ada di log"
echo "  • Merge hanya file baru ke glmap.mbtiles"
echo "  • Update log dengan file yang baru dimerge"
echo "  • Total waktu: ~2-5 detik untuk 1 file baru!"
echo ""

echo "Grid Layer:"
echo "  • Convert SHP ke mbtiles (sekali saja)"
echo "  • Simpan sebagai grid_layer.mbtiles"
echo "  • Tampil sebagai base layer (pink grid)"
echo "  • GLMap tampil di atasnya (overlay)"
echo ""

echo "🎨 STYLE CONFIGURATION:"
echo "════════════════════════"
echo "File: /app/styles/default/style.json"
echo "Layers:"
echo "  1. grid-fill   - Pink semi-transparent fill"
echo "  2. grid-line   - Blue outline"
echo "  3. glmap-raster - Drone imagery overlay"
echo ""

echo "⚙️  CONFIGURATION OPTIONS:"
echo "═══════════════════════════"
echo "Environment Variables:"
echo "  DATA_DIR=/custom/path        - Custom data directory"
echo "  SKIP_DB_UPDATE=true          - Skip PostgreSQL update"
echo "  FORCE_STYLE_UPDATE=true      - Recreate style.json"
echo "  MERGE_LOG=/custom/.log       - Custom merge log location"
echo ""

echo "🔧 TROUBLESHOOTING:"
echo "════════════════════"
echo "Q: Grid layer tidak muncul?"
echo "A: Install tippecanoe atau run convert-grid-raster.sh"
echo ""
echo "Q: Ingin reset dan merge ulang semua?"
echo "A: rm /app/data/.merged_files.log && rm /app/data/glmap.mbtiles"
echo ""
echo "Q: File baru tidak kemerge?"
echo "A: Check .merged_files.log - pastikan filename belum ada di sana"
echo ""
echo "Q: Ingin lihat file mana saja yang sudah dimerge?"
echo "A: cat /app/data/.merged_files.log"
echo ""

echo "📈 PERFORMANCE COMPARISON:"
echo "═══════════════════════════"
echo "Traditional (merge all from scratch):"
echo "  • 50 files × 1365 tiles = ~2-5 minutes"
echo ""
echo "Incremental (new approach):"
echo "  • First run: same as traditional (one time)"
echo "  • Subsequent: 1 new file = ~2-5 seconds ⚡"
echo "  • 10x - 100x FASTER!"
echo ""

echo "✅ EXPECTED RESULTS:"
echo "═════════════════════"
echo "Web interface akan menampilkan:"
echo "  1. Grid layer (pink grid 36 HA)"
echo "  2. GLMap (merged drone imagery di atas grid)"
echo "  3. Individual drone files (optional viewing)"
echo ""

echo "Total datasets: ~60+ (grid + glmap + individual files)"
echo "Loading time: Minimal (incremental merge)"
echo "Visual result: Grid dengan drone imagery overlay ✨"
echo ""

echo "📝 FILES CREATED:"
echo "══════════════════"
echo "/app/data/grid_layer.mbtiles    - Grid base layer (created once)"
echo "/app/data/glmap.mbtiles          - Merged drone imagery"
echo "/app/data/.merged_files.log      - Tracking log"
echo "/app/config.json                 - Tileserver config"
echo "/app/styles/default/style.json   - Multi-layer style"
echo ""

echo "🎯 READY TO USE!"
echo "════════════════"
echo "Run this to start:"
echo "  chmod +x generate-config-incremental.sh"
echo "  ./generate-config-incremental.sh"
echo ""