#!/bin/bash

# README: Generate Config with PostgreSQL Update
# Script generate-config-simple.sh dengan fitur update database

echo "=== Generate Config Script with PostgreSQL Update ==="
echo ""

echo "📋 FEATURES:"
echo "1. ✓ Generate tileserver-gl config.json"
echo "2. ✓ Merge valid .mbtiles files into glmap.mbtiles" 
echo "3. ✓ Skip corrupt _trails files automatically"
echo "4. ✓ Extract coordinates from mbtiles metadata"
echo "5. ✓ Update PostgreSQL database with coordinates"
echo "6. ✓ Restart tileserver container"
echo ""

echo "🔧 REQUIREMENTS:"
echo "- Ubuntu 24.4 server"
echo "- sqlite3 (for mbtiles processing)"
echo "- python3 (for JSON validation and database)"
echo "- docker (for container restart)"
echo "- Internet connection (for pip install psycopg2)"
echo ""

echo "📂 EXPECTED FILE STRUCTURE:"
echo "/app/data/             # Data directory"
echo "├── *.mbtiles          # Valid mbtiles files" 
echo "├── *_trails.mbtiles   # Corrupt files (auto-skipped)"
echo "└── glmap.mbtiles      # Generated merged file"
echo ""
echo "/app/config.json       # Generated config"
echo "/app/styles/default/   # Style directory"
echo ""

echo "🗄️ DATABASE SETUP:"
echo "Host: 172.26.11.153"
echo "User: pg"
echo "Database: postgres"
echo "Table: geoportal.pmn_drone_imagery"
echo "Fields updated: latitude, longitude, updated_at"
echo "Match by: storage_path LIKE '%filename.mbtiles%'"
echo ""

echo "🚀 USAGE:"
echo "# Basic usage"
echo "./generate-config-simple.sh"
echo ""
echo "# Skip database update"
echo "SKIP_DB_UPDATE=true ./generate-config-simple.sh"
echo ""
echo "# Custom data directory"
echo "DATA_DIR=/custom/path ./generate-config-simple.sh"
echo ""

echo "📤 EXPECTED OUTPUT:"
echo "✓ Config with glmap + individual valid files"
echo "✓ Database records updated with coordinates" 
echo "✓ Tileserver container restarted"
echo "✓ Web interface shows all datasets"
echo ""

echo "🔍 COORDINATE EXTRACTION:"
echo "1. Try bounds from mbtiles metadata"
echo "2. Try center from mbtiles metadata"
echo "3. Fallback to Indonesia default (-0.469, 117.172)"
echo ""

echo "🎯 EXPECTED RESULTS:"
echo "Based on your files, should generate:"
echo "- glmap (merged tiles from all valid files)"
echo "- 9 individual datasets (excluding _trails)"
echo "- Total: 10 datasets in tileserver interface"
echo ""

echo "📝 DATABASE UPDATES:"
echo "Files processed for coordinate update:"
echo "- 1761574836479_54098_32852"
echo "- 1761575194145_54097_32853"
echo "- 1761575406079_54097_32853"
echo "- 1761575459307_x54097_32853"
echo "- 1761575908071_Y54097_32853"
echo "- 1762157419255_1761574836479_54098_32852"
echo "- 1762161762447_54097_32853"
echo "- 1762161952415_1761575908071_Y54097_32853"
echo "- 1762255721780_1762157419255_1761574836479_54098_32852"
echo "- glmap"
echo ""

echo "⚠️ TROUBLESHOOTING:"
echo "- If psycopg2 install fails: Database update will be skipped"
echo "- If bc not available: Will use awk for calculations"
echo "- If no bounds in mbtiles: Will use default coordinates"
echo "- If docker not available: Manual container restart required"
echo ""

echo "Script ready to run! 🚀"