#!/bin/bash

# README: Enhanced Generate Config dengan Incremental Merge & Grid Layer

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   Enhanced Tileserver Config Generator dengan Grid Layer      ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 NEW FEATURES:"
echo "════════════════"
echo "1. ✨ INCREMENTAL MERGE - Hanya merge file baru (tidak dari awal)"
echo "2. 🗺️  GRID LAYER - Tambah layer SHP sebagai base layer"
echo "3. 📊 MERGE TRACKING - Log file yang sudah dimerge"
echo "4. ⚡ FAST UPDATES - Upload file baru jadi cepat!"
echo ""

echo "🎯 LAYER STACK (2-Layer XYZ Approach):"
echo "═══════════════════════════════════════"
echo "  Layer 1: grid_layer - Base grid overview (zoom 0-14)"
echo "           URL: https://glserver.ptnaghayasha.com/data/grid_layer/{z}/{x}/{y}.pbf"
echo ""
echo "  Layer 2: glmap - Drone imagery overlay (zoom 16-22)"
echo "           URL: https://glserver.ptnaghayasha.com/data/glmap/{z}/{x}/{y}.jpg"
echo ""
echo "  🎨 Add both layers to your Leaflet/Mapbox GL JS application!"
echo ""

echo "📂 FILE STRUCTURE:"
echo "═══════════════════"
echo "/app/data/"
echo "├── grid_layer.mbtiles                     (Grid tiles - SEPARATE, not merged)"
echo "├── glmap.mbtiles                          (Merged DRONE tiles ONLY)"
echo "├── .merged_files.log                      (Tracking merged drone files)"
echo "└── *.mbtiles                              (Individual drone imagery)"
echo ""
echo "⚠️  IMPORTANT: grid_layer.mbtiles is EXCLUDED from merge process!"
echo "              It's served as separate XYZ layer in config.json"
echo ""

echo "🚀 INSTALLATION & SETUP:"
echo "═════════════════════════"
echo "Step 1: Install Tippecanoe (untuk vector tiles)"
echo "  ./install-tippecanoe.sh"
echo ""
echo "Step 2 (Alternative): Jika tippecanoe gagal, gunakan GDAL"
echo "  ./convert-grid-raster.sh"
echo ""
echo "Step 3: Run generate config pertama kali"
echo "  ./generate-config-incremental.sh"
echo ""

echo "💡 WORKFLOW - FIRST TIME:"
echo "══════════════════════════"
echo "1. Upload semua file .mbtiles ke /app/data/"
echo "2. Pastikan folder GRID_DRONE_36_HA_EKSISTING_POTENSI 3/ ada"
echo "3. Run: ./generate-config-incremental.sh"
echo "4. Wait... (pertama kali akan merge semua file)"
echo "5. Done! Container restart otomatis"
echo ""

echo "⚡ WORKFLOW - UPLOAD FILE BARU:"
echo "════════════════════════════════"
echo "1. Upload file baru .mbtiles ke /app/data/"
echo "2. Run: ./generate-config-incremental.sh"
echo "3. Done! (hanya merge file baru - SUPER CEPAT!)"
echo ""

echo "📊 HOW IT WORKS:"
echo "═════════════════"
echo "Incremental Merge Logic:"
echo "  • Script check file .merged_files.log"
echo "  • Filter out 'grid_layer.mbtiles' from merge process"
echo "  • Cari file drone yang belum ada di log"
echo "  • Merge hanya file DRONE baru ke glmap.mbtiles"
echo "  • Update log dengan file yang baru dimerge"
echo "  • Total waktu: ~2-5 detik untuk 1 file baru!"
echo ""

echo "Grid Layer (Separate):"
echo "  • grid_layer.mbtiles served independently"
echo "  • NOT merged into glmap.mbtiles"
echo "  • Vector tiles (PBF format) - zoom 0-14"
echo "  • XYZ URL: /data/grid_layer/{z}/{x}/{y}.pbf"
echo ""

echo "GLMap Layer (Drone Only):"
echo "  • glmap.mbtiles contains ONLY drone imagery"
echo "  • Raster tiles (JPG format) - zoom 16-22"
echo "  • XYZ URL: /data/glmap/{z}/{x}/{y}.jpg"
echo ""

echo "🎨 XYZ TILE URLS:"
echo "════════════════════════"
echo "Grid Layer (Vector):"
echo "  https://glserver.ptnaghayasha.com/data/grid_layer/{z}/{x}/{y}.pbf"
echo "  Format: PBF (vector tiles)"
echo "  Zoom: 0-14"
echo ""
echo "GLMap Layer (Raster):"
echo "  https://glserver.ptnaghayasha.com/data/glmap/{z}/{x}/{y}.jpg"
echo "  Format: JPG (raster tiles)"
echo "  Zoom: 16-22"
echo ""
echo "📱 Frontend Integration:"
echo "  Add both layers to your mapping application (Leaflet/Mapbox GL JS)"
echo "  Use appropriate renderer for each format (vector vs raster)"
echo ""

echo "⚙️  CONFIGURATION OPTIONS:"
echo "═══════════════════════════"
echo "Environment Variables:"
echo "  DATA_DIR=/custom/path        - Custom data directory"
echo "  SKIP_DB_UPDATE=true          - Skip PostgreSQL update"
echo "  FORCE_STYLE_UPDATE=true      - Recreate style.json"
echo "  MERGE_LOG=/custom/.log       - Custom merge log location"
echo ""

echo "🔧 TROUBLESHOOTING:"
echo "════════════════════"
echo "Q: Grid tidak muncul di aplikasi?"
echo "A: Check URL grid_layer di frontend, pastikan menggunakan vector tile renderer"
echo ""
echo "Q: Grid_layer.mbtiles termerge ke glmap?"
echo "A: Script sudah exclude 'grid_layer.mbtiles' otomatis, check logs"
echo ""
echo "Q: Ingin reset dan merge ulang semua drone files?"
echo "A: rm /app/data/.merged_files.log && rm /app/data/glmap.mbtiles"
echo ""
echo "Q: File baru tidak kemerge?"
echo "A: Check .merged_files.log - pastikan filename belum ada di sana"
echo ""
echo "Q: Ingin lihat file mana saja yang sudah dimerge?"
echo "A: cat /app/data/.merged_files.log | grep -v grid_layer"
echo ""
echo "Q: Format error saat merge?"
echo "A: Normal! grid_layer (vector) dan drone (raster) sekarang terpisah"
echo ""

echo "📈 PERFORMANCE COMPARISON:"
echo "═══════════════════════════"
echo "Traditional (merge all from scratch):"
echo "  • 50 files × 1365 tiles = ~2-5 minutes"
echo ""
echo "Incremental (new approach):"
echo "  • First run: same as traditional (one time)"
echo "  • Subsequent: 1 new file = ~2-5 seconds ⚡"
echo "  • 10x - 100x FASTER!"
echo ""

echo "✅ EXPECTED RESULTS:"
echo "═════════════════════"
echo "Config.json akan berisi:"
echo "  1. grid_layer dataset (vector tiles - separate)"
echo "  2. glmap dataset (drone imagery - merged, NO grid)"
echo "  3. Individual drone files (optional viewing)"
echo ""

echo "Total datasets: ~60+ (grid_layer + glmap + individual files)"
echo "File count: grid_layer excluded from merge tracking"
echo "Merge speed: Fast (only processes drone files)"
echo ""

echo "🎯 Application Setup:"
echo "  → Add grid_layer XYZ URL for base grid"
echo "  → Add glmap XYZ URL for drone overlay"
echo "  → Grid shows at zoom 0-14, drone at zoom 16-22"
echo ""

echo "📝 FILES CREATED:"
echo "══════════════════"
echo "/app/data/grid_layer.mbtiles    - Grid base layer (created once)"
echo "/app/data/glmap.mbtiles          - Merged drone imagery"
echo "/app/data/.merged_files.log      - Tracking log"
echo "/app/config.json                 - Tileserver config"
echo "/app/styles/default/style.json   - Multi-layer style"
echo ""

echo "🎯 READY TO USE!"
echo "════════════════"
echo "Run this to start:"
echo "  chmod +x generate-config-incremental.sh"
echo "  ./generate-config-incremental.sh"
echo ""